trigger:
  - main

pool: Roboshop-workstation

steps:
  - script: npm install
    displayName: 'Download Nodejs Dependencies'

  - script: docker build -t cart .
    displayName: 'Docker build cart image'